services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: expense-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  expense-api:
    build:
      context: .
      dockerfile: ExpenseManagement/Dockerfile
    container_name: expense-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=db;Database=Expense;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true;
      Jwt__Key: CHAVE_SUPER_SECRETA_COM_PELO_MENOS_32_CHARS_MINIMO_PARA_SEGURANCA
      Jwt__Issuer: ExpenseApi
      Jwt__Audience: ExpenseWeb
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - api-uploads:/app/wwwroot/uploads

  expense-web:
    build:
      context: .
      dockerfile: ExpenseWeb/Dockerfile
    container_name: expense-web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      ServiceUri__ExpenseApi: http://expense-api:8080
    depends_on:
      - expense-api
    ports:
      - "8081:8081"

volumes:
  mssql-data:
  api-uploads:
